services:
    markethub.submarino.client:
        class: Gpupo\SubmarinoSdk\Client
        arguments: [markethub.submarino, @?logger]
        tags:
            - { name: monolog.logger, channel: product }
    markethub.submarino.product.manager:
        class: Gpupo\SubmarinoSdk\Entity\Product\Manager
        arguments: [@markethub.submarino.client]
    markethub.submarino.product.sku.manager:
        class: Gpupo\SubmarinoSdk\Entity\Product\Sku\Manager
        arguments: [@markethub.submarino.client]
    markethub.submarino.order.manager:
        class: Gpupo\SubmarinoSdk\Entity\Order\Manager
        arguments: [@markethub.submarino.client]
