name: CI
on: []
  pull_request:
    branches:
      - develop
  push:
    branches:
      - "main"
  create:
      tags: '*'
jobs:
  run:
    name: Run
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['8.0']
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Validate composer.json
        run: composer validate

      - name: Install dependencies
        run: make install

      - name: Run test suite
        run: composer run-script test
